### ISSUE TITLE
Clarification Needed on `Task` vs `Command`

### ISSUE THREAD

**Issue by tigitz** [jolicode/castor#231]
While going through the Castor documentation, I encountered some confusion regarding the terms 'task' and 'command'. The introduction section refers to Castor as a "task runner and command launcher," but as I delved deeper, the distinction between these two terms became unclear.

For example, to create and run a command, the documentation instructs to use the `#[AsTask]` attribute.
![image](https://github.com/jolicode/castor/assets/1524501/9043af77-c3c2-4e9a-925a-5d6af9487c02)

This usage suggests that a Command is equivalent to a Task. However, if that's the case, why are two different terms used? This is particularly perplexing.

To provide some context, I'm familiar with Taskfile, a popular Makefile alternative, which Castor lists as a comparable tool. In Taskfile, tasks are defined as a set of commands. You execute a task, which in turn runs multiple commands. 
![image](https://github.com/jolicode/castor/assets/1524501/6a1a3336-ca1d-4c59-8671-f09203ccacd6)

Drawing from this, running `task prod-to-local` in Taskfile is executing a task, whereas `castor prod-to-local` in Castor is described as executing a command. So, what exactly constitutes a task in Castor? It's supposed to be a task runner too right ?

This terminology ambiguity seems to extend from the code to the documentation, and I believe Castor could greatly benefit from more precise and consistent language. This was notably pointed out in a recent review suggestion: [https://github.com/jolicode/castor/pull/218#discussion_r1446018497](https://github.com/jolicode/castor/pull/218#discussion_r1446018497).

**Comment by pyrech** [comment]
I guess most of the confusion comes from the fact that our tasks are in fact based on Symfony Console's Commands. So to execute a Castor task, you need to execute the related Symfony-ish command behind.

As Symfony developpers, we are quite used to this naming but in order to fix the confusion, I guess we should consider Symfony commands an implementation detail and stick to the `Task` naming everywhere :+1:

**Comment by joelwurtz** [comment]
About the naming, for me a command is a task that is executed on a console, so basically in our case both are similar since all our task are meant to be execute on a console. @pyrech explain why we use task instead of command (to not confuse about the `Command` way of symfony) i understand your confusion also, we should mostly use task, and maybe sometimes use `console command` to enforce our view instead of only `command`

**Comment by tigitz** [comment]
> As Symfony developpers, we are quite used to this naming

Coming from Symfony too, that was my guess.

>  I guess we should consider Symfony commands an implementation detail and stick to the Task naming everywhere 👍

Fully agree, IMO this is the best course of action in order to reinforce Castor's identity as a genuine Task Runner, It will also help establish Castor as a solid alternative to other Task Runners.

**Comment by lyrixx** [comment]
> This usage suggests that a Command is equivalent to a Task. However, if that's the case, why are two different terms used? This is particularly perplexing.

👍🏼 



> > I guess we should consider Symfony commands an implementation detail and stick to the Task naming everywhere 👍

👍🏼 

@tigitz Do you want to work on this?

**Comment by tigitz** [comment]
Sure, let's do it 👍
