### ISSUE TITLE
curl command not working on MacOs - "Could not install castor. Is the target directory writeable?" error

### ISSUE THREAD

**Issue by kyrog** [jolicode/castor#253]
When i am pasting the following command : 

curl "https://github.com/jolicode/castor/releases/latest/download/castor.darwin-amd64.phar" -Lfso /usr/local/bin/castor && \
    chmod u+x /usr/local/bin/castor && \
    castor --version || \
    (echo "Could not install castor. Is the target directory writeable?" && (exit 1))

it echo the error message "Could not install castor. Is the target directory writeable?", even when i use sudo mode.

**Comment by TheoD02** [comment]
Hey,

Did you have a `.local/bin` directory in your `$HOME` directory ?

- [ ] Directory exists ? Yes ⇒ Make sure that the user has write permissions (drwxr-xr-x or similar).
```bash
ls -ld $HOME/.local/bin/
```

- [ ] Directory exists ? No ⇒ Create the Target Directory if it Doesn't Exist
```bash
mkdir -p $HOME/.local/bin/
```

Re-run the first `ls -ld $HOME/.local/bin/` to check is permissions is OK

Now re-run the castor installation command 😃 

Ensure to add `$HOME/.local/bin` to your `PATH` depending on what shell you use 😄 

For bash :
```bash
export PATH="$HOME/.local/bin:$PATH"
```

Add this line at the end of `~/.bashrc` for **bash only** for preventing run this command on each restart, otherwise check for your shell 🍒

**Comment by kyrog** [comment]
Indeed the directory wasn't existing. So :
- i created the directory
- i had to run each command one by one (instead of the full one with &&)
- export the path 

and it worked ! thank you for your help 👍

**Comment by lyrixx** [comment]
Hello, 

Thanks you for your report. This is very appreciated.

First, in the title you said
>curl command not working on MacOs - "Could not install castor. Is the target directory writeable?" error #253

But in the description you said:
```
curl "https://github.com/jolicode/castor/releases/latest/download/castor.darwin-amd64.phar" -Lfso /usr/local/bin/castor &&
chmod u+x /usr/local/bin/castor &&
castor --version ||
(echo "Could not install castor. Is the target directory writeable?" && (exit 1))```

This is not a command for MacOS. The command for Mac is documented [here](https://github.com/jolicode/castor/blob/main/doc/01-installation.md)
```
curl "https://github.com/jolicode/castor/releases/latest/download/castor.darwin-amd64.phar" -Lfso /usr/local/bin/castor && \
    chmod u+x /usr/local/bin/castor && \
    castor --version || \
    (echo "Could not install castor. Is the target directory writeable?" && (exit 1))
```

---

Then, Thanks a lot to @TheoD02 for helping you. It looks like you both managed to make it work on MacOS (or linux, I'm sure sure what system you are using 😅)

---

Anyway, I'm closing this issue since it looks like nothing is broken. But If you think we can do something better, don't hesitate to open a PR 💛
