### ISSUE TITLE
install via a bundle, like tailwind

### ISSUE THREAD

**Issue by tacman** [jolicode/castor#255]
The installation part of castor is a bit intimidating.  The tailwind bundle downloads the file to make it a seamless experience.

https://github.com/SymfonyCasts/tailwind-bundle

I deploy my apps to dokku (a heroku-like server), and often run commands like

    dokku run "bin/console app:create-project test"

If I change these to castor, I have to figure out how to install it on the production server, but it if were in a bundle that did the install, perhaps I wouldn't need that step at all.

**Comment by lyrixx** [comment]
Hello, Thanks for the proposal, but I think the bundle way if a wrong path.
Not all applications use Symfony. 

More over, if we go this path, it means we cannot use castor to install the projet, since vendor are missing! 

The Tailwind bundle download the tailwind binary but does more things. It's not really comparable here.

So I'm 👎🏼 for this contribution. Sorry

---

>The installation part of castor is a bit intimidating.

Actually, It's a matter of copying a binary to somewhere in your PATH, and adding the executable flag:

```bash
curl "https://github.com/jolicode/castor/releases/latest/download/castor.linux-amd64.phar" -Lfso $HOME/.local/bin/castor && chmod u+x $HOME/.local/bin/castor
```

I fail to see how we can make it simpler.

---

Maybe we should create an installer [like composer](https://getcomposer.org/download/), but it could also be intimidating.

We could also support an APT/YUM repository, of some userland repository like homebrew & co.

But this is extra maintenance for us, and IMHO this does not wort it for now.

**Comment by lyrixx** [comment]
we highly **NOT** recommend to install castor in your SF application. Castor is a tool, and like each tool it should not be embed in the application.

If you do that, it means download again and again castor in every application. This is a waste a disk usage, bandwidth, etc.

It's much better to install it globally, as stated in the documentation.

If you still want to do this, you can, but it's not supported. Sorry.

> Downloading the binary means getting my devops involved in the build process, that's what I'm trying to avoid.

But castor **is** a devops tools. Excluding it from the build processes is a bad idea. 

Thanks for the idea, but I'm gonna close this issue.
