### ISSUE TITLE
Bad “vendor” folder embedded in .phar throws an error "Class not found"

### ISSUE THREAD

**Issue by arnolem** [jolicode/castor#477]
Hello,

I don't understand how the `castor composer` command works when transforming the application into PHAR.

I used `castor composer require` and I have a `.castor/vendor` folder with my dependencies.
![image](https://github.com/jolicode/castor/assets/2263103/2e1d2e70-02b5-4eed-945b-31ba775cbcc5)

But when I convert the application to PHAR, it is not this folder which is embedded but the vendor which is at the root of the project
![image](https://github.com/jolicode/castor/assets/2263103/f73ed9c4-b164-41d3-81a8-77e3bc5fc995)

![image](https://github.com/jolicode/castor/assets/2263103/1e713d3c-6b74-4814-b384-dbe40d024221)

Because of this, the compiled application does not work because the dependencies do not exist

What didn't I understand? Is there a problem ?

Thanks 🙏

**Comment by joelwurtz** [comment]
Hey can you try https://github.com/jolicode/castor/pull/481 ?

It should fix your issue. 

In fact we need to include this vendor directory since we need castor and our dependencies to make castor work on your repacked application.

We are not sure about implication of having to include both of those directories so instead we only copy castor.composer.json file

**Comment by arnolem** [comment]
Thanks @joelwurtz .
Sorry, it doesn't work.

composer.json
```json
{
  "require": {
    "jolicode/castor": "dev-main#f4e0e8a25f950b738ff3834592ea61f34bdb6306"
  },
  "config": {
    "allow-plugins": {
      "php-http/discovery": true
    }
  }
}
```

```bash
composer update
```

```bash
repack --app-name=$name --app-version=$version
```
❌ bad vendor folder
![image](https://github.com/jolicode/castor/assets/2263103/2f7102fd-cfd6-43a1-9a04-2231865af4d5)

❌ Class not found
![image](https://github.com/jolicode/castor/assets/2263103/c6fde25a-8cff-4411-ba65-15a294f6a5cf)

Was I wrong?

**Comment by joelwurtz** [comment]
Should be good with https://github.com/jolicode/castor/pull/485

I reproduce the problem and fix it with that

However i'm wondering if you should use this approach, in this scenario you should use "composer" instead of "castor composer" i don't think it add any value to split the two ?

**Comment by arnolem** [comment]
Indeed, now both files are imported and I no longer have a problem.

Thanks.

I thought that the "castor composer" version allowed me to choose what is useful for my application so as not to include the "vendor" which allows "castor" to work and compile for example.

But if both are encapsulated now, I don't quite understand. Especially since I was doing things differently before and you advised me to change: https://github.com/jolicode/castor/issues/456#issuecomment-2098527406

Do you have an easy way to choose between `castor composer` and `composer` ?

Thanks

**Comment by joelwurtz** [comment]
With our current philosophy it doesn't change much to include castor dep directly in your composer when you repack. As in both case we don't provide the composer command into the repacked application as we think this approach if for people that don't want it to change overtime.

Also it should be safer since you ensure that dependencies are compatible between each others.

We may in the future allow composer in the repacked application and not include files from ".castor" directory, so it would provide a middle step where you allow the dependencies on your castor files to change. But IMO this requirement is niche and don't think we will do that in the near future.

**Comment by arnolem** [comment]
Alright, but I don't quite understand when to use castor composer instead of composer.
Thanks for this fix and this advice 👍
