### ISSUE TITLE
Allow defining a default task when running `castor`

### ISSUE THREAD

**Issue by ruudk** [jolicode/castor#539]
It would be great if I could define a default task, that should be executed when I run `castor` without providing any arguments.

Currently I type `castor qa` but ideally I just type `castor` and it will invoke my `qa` task.

**Comment by lyrixx** [comment]
I think it's doable with https://github.com/symfony/symfony/blob/7.2/src/Symfony/Component/Console/Application.php#L1239

But since we have only one command for all task, I don't know how it could work for now... 

Maybe we should add a virtual (anonymous class) that map to the default task.

Do you want to give it a try?
